# Generated by Django 3.1.7 on 2021-03-30 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='OLT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olt_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='OvccData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downtime', models.DateTimeField(auto_now=True)),
                ('uptime', models.DateTimeField()),
                ('informed_to', models.CharField(max_length=25)),
                ('down_self', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oltcheck.category')),
                ('olt_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oltcheck.olt')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oltcheck.province')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oltcheck.reason')),
            ],
        ),
        migrations.CreateModel(
            name='Oltdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olt_name', models.CharField(max_length=25)),
                ('downtime', models.DateTimeField(auto_now=True)),
                ('uptime', models.DateTimeField(null=True)),
                ('informed_to', models.CharField(max_length=25)),
                ('reason', models.CharField(max_length=25)),
                ('category', models.CharField(max_length=25)),
                ('down_self', models.BooleanField(default=True)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oltcheck.province')),
            ],
        ),
        migrations.AddField(
            model_name='olt',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oltcheck.province'),
        ),
    ]
