# Generated by Django 3.1.7 on 2021-04-08 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=25)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oltcheck.category')),
            ],
        ),
        migrations.CreateModel(
            name='Oltdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olt_name', models.CharField(max_length=25)),
                ('downtime', models.DateTimeField(auto_now=True)),
                ('uptime', models.DateTimeField(blank=True)),
                ('informed_to', models.CharField(max_length=25)),
                ('reason', models.CharField(default='', max_length=25)),
                ('down_self', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oltcheck.category')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oltcheck.province')),
            ],
        ),
        migrations.CreateModel(
            name='OLT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olt_name', models.CharField(max_length=25)),
                ('client_count', models.CharField(blank=True, max_length=25)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oltcheck.province')),
            ],
        ),
    ]
