# Generated by Django 3.1.7 on 2021-03-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltcheck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='client_count',
            field=models.IntegerField(null=True),
        ),
    ]
