# Generated by Django 3.2 on 2021-04-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltcheck', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oltdown',
            name='down_self',
            field=models.BooleanField(default=False),
        ),
    ]
