# Generated by Django 3.1.7 on 2021-03-31 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oltcheck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_count', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='reason',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oltcheck.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oltdown',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oltcheck.category'),
        ),
        migrations.DeleteModel(
            name='OvccData',
        ),
        migrations.AddField(
            model_name='olt',
            name='client_count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oltcheck.clientcount'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='oltdown',
            name='client_count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oltcheck.clientcount'),
            preserve_default=False,
        ),
    ]
