# Generated by Django 3.1.7 on 2021-04-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltcheck', '0002_auto_20210408_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='oltdown',
            name='client_count',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
