# Generated by Django 3.1.7 on 2021-03-31 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oltcheck', '0002_auto_20210331_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oltdown',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='oltcheck.category'),
        ),
        migrations.AlterField(
            model_name='oltdown',
            name='reason',
            field=models.CharField(default='', max_length=25),
        ),
    ]
