# Generated by Django 3.1.7 on 2021-03-31 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oltcheck', '0003_auto_20210331_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oltdown',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oltcheck.category'),
        ),
    ]
