# Generated by Django 3.1.7 on 2021-04-10 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oltcheck', '0003_oltdown_client_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oltdown',
            name='informed_to',
            field=models.CharField(choices=[('RF Duty Managers', 'RF Duty Managers'), ('SPR', 'SPR'), ('Province Team', 'Province Team'), ('L2', 'L2'), ('Power', 'Power')], max_length=25),
        ),
        migrations.AlterField(
            model_name='oltdown',
            name='olt_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oltcheck.olt'),
        ),
    ]
