# Generated by Django 3.1.7 on 2021-03-30 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oltcheck', '0003_oltdown_client_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='olt',
            name='client_count',
        ),
        migrations.AlterField(
            model_name='olt',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oltcheck.clientcount'),
        ),
    ]
