# Generated by Django 3.1.7 on 2021-04-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltcheck', '0004_auto_20210410_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oltdown',
            name='informed_to',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='oltdown',
            name='olt_name',
            field=models.CharField(max_length=25),
        ),
    ]
