# Generated by Django 3.1.7 on 2021-03-30 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oltcheck', '0004_auto_20210330_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='olt',
            name='client_count',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oltcheck.clientcount'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='olt',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oltcheck.province'),
        ),
    ]
