# Generated by Django 3.1.7 on 2021-03-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltcheck', '0005_auto_20210330_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcount',
            name='client_count',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
