# Generated by Django 3.1.7 on 2021-04-10 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oltcheck', '0005_auto_20210410_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oltdown',
            name='informed_to',
            field=models.CharField(choices=[('RF Duty Managers', 'RF Duty Managers'), ('SPR', 'SPR'), ('Province Team', 'Province Team'), ('L2', 'L2'), ('Power', 'Power')], max_length=25),
        ),
        migrations.AlterField(
            model_name='oltdown',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
