# Generated by Django 3.1.7 on 2021-03-30 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oltcheck', '0006_auto_20210330_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oltdown',
            name='client_count',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oltcheck.clientcount'),
        ),
    ]
